name: pre_merge_checks
on:
  pull_request:
    branches:
      - '*'

env:
  TERM: dumb
  IMAGE_VERSION: 9.99.9
jobs:
  build_base:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.0
    - run: IMAGE_NAME=android_base DOCKER_FILE_PATH=android_base/. ./.github/docker_build_image.sh
    - run: IMAGE_NAME=android DOCKER_FILE_PATH=. ./.github/docker_build_image.sh
